// Imported by BOTH the browser bundle and the /api backend.
// These UIDs are assigned explicitly by scripts/bootstrap.mjs rather than generated by
// Firebase, so they are identical in the emulator and in production and never need
// substituting. Keep identical to superAdmins() in firestore.rules — tests/roles.test.js
// parses that file and fails if they differ.
export const SUPER_ADMIN_UIDS = Object.freeze([
  "sa_yash",
  "sa_titus",
  "sa_gebin",
]);

export const ROLES = Object.freeze(["superadmin", "admin", "member"]);

export function isSuperAdmin(uid) {
  return typeof uid === "string" && SUPER_ADMIN_UIDS.includes(uid);
}

export function effectiveRole(uid, storedRole) {
  if (isSuperAdmin(uid)) return "superadmin";
  return ROLES.includes(storedRole) && storedRole !== "superadmin" ? storedRole : "member";
}

export function canManageUsers(role) {
  return role === "superadmin" || role === "admin";
}

export function canAssignRoles(role) {
  return role === "superadmin";
}

export function canActOn({ actorUid, actorRole, targetUid, targetRole }) {
  // Nobody, including the other super-admin, may act on a super-admin.
  if (isSuperAdmin(targetUid)) return false;
  if (actorUid === targetUid) return false;
  if (actorRole === "superadmin") return true;
  if (actorRole === "admin") return targetRole === "member";
  return false;
}
